### ISSUE TITLE
Fetching no longer existing user/fork breaks ght-retrieve-repo

### ISSUE THREAD

**Issue by gordongli** [gousiosg/github-mirror#63]
```
WARN, 2018-03-02T15:22:53-08:00, ghtorrent -- api_client.rb: Failed request. URL: https://api.github.com/repos/Crockchartering/twitter.github.com, Status code: 404, Status: Not Found, Access: 336331c85fc, IP: 0.0.0.0, Remaining: 4367
ERROR, 2018-03-02T15:22:53-08:00, ghtorrent -- full_repo_retriever.rb: Error in stage: ensure_forks, Repo: twitter/twitter.github.com, Message: no implicit conversion of String into Integer
/home/gordonl/github-mirror/lib/ghtorrent/retriever.rb:694:in `[]='
/home/gordonl/github-mirror/lib/ghtorrent/retriever.rb:694:in `block (3 levels) in repo_bound_items'
/home/gordonl/github-mirror/lib/ghtorrent/retriever.rb:683:in `each'
/home/gordonl/github-mirror/lib/ghtorrent/retriever.rb:683:in `block (2 levels) in repo_bound_items'
/home/gordonl/github-mirror/lib/ghtorrent/retriever.rb:679:in `each'
/home/gordonl/github-mirror/lib/ghtorrent/retriever.rb:679:in `block in repo_bound_items'
/home/gordonl/github-mirror/lib/ghtorrent/retriever.rb:670:in `each'
/home/gordonl/github-mirror/lib/ghtorrent/retriever.rb:670:in `repo_bound_items'
/home/gordonl/github-mirror/lib/ghtorrent/retriever.rb:354:in `retrieve_forks'
/home/gordonl/github-mirror/lib/ghtorrent/ghtorrent.rb:1388:in `ensure_forks'
/home/gordonl/github-mirror/lib/ghtorrent/commands/full_repo_retriever.rb:87:in `block in retrieve_full_repo'
/home/gordonl/github-mirror/lib/ghtorrent/commands/full_repo_retriever.rb:84:in `each'
/home/gordonl/github-mirror/lib/ghtorrent/commands/full_repo_retriever.rb:84:in `retrieve_full_repo'
/home/gordonl/github-mirror/lib/ghtorrent/commands/ght_retrieve_repo.rb:31:in `go'
/home/gordonl/github-mirror/lib/ghtorrent/command.rb:66:in `run'
bin/ght-retrieve-repo:6:in `<main>'
```

**Comment by dong-qiu** [comment]
I also have the same issue. Did anyone solve this problem?
